# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4464a602c553389803b074c60b0b5132e6924a09ce1335fec5c6a5a5b4297eca59c55844eea590d26ce23e52cb6faa030b4a9ea143b49b8f5d09e198cede9e2f

test:
  secret_key_base: 09b790a5c5666aec15debcb33dc3fd7af9fb67c81eb7b765683e7c760ab5dd60be7eb98eaa4c482264462fe324461c06ae1eae2999677a7bd0d696bce6d65cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
